export interface Store {
    tienda: string;
    codigo: string;
    marca: string;
    tipo: string;
    direccion: string;
    colonia: string;
    municipio: string;
    codigo_postal: string;
    estado: string;
    telefono: string;
    correo: string;
}

export const stores: Store[] = [
    {
        tienda: 'LOB Footwear La Perla',
        codigo: 'FW111',
        marca: 'Footwear',
        tipo: 'tienda',
        direccion: 'Av. Mariano Otero #3000, Local B-207A Nivel 1',
        colonia: 'Jardines del Sol',
        municipio: 'Guadalajara',
        codigo_postal: '45050',
        estado: 'Jalisco',
        telefono: '3336220569',
        correo: 'lobfw.@com.mx',
        latitud: '20.6738707',
        longitud: '-103.3805708',
    },
    {
        tienda: 'Plaza Mayor León',
        codigo: 'T1003',
        marca: 'Hallmark',
        tipo: 'tienda',
        direccion: 'Boulevard Juan Alonso de Torres #2002, Local L-1230',
        colonia: 'Valle del Campestre',
        municipio: 'León',
        codigo_postal: '37150',
        estado: 'Guanajuato',
        telefono: '4771027500',
        correo: 't1003@lob.com.mx',
        latitud: '21.15672351752534',
        longitud: '-101.69660716812511',
    },
    {
        tienda: 'Plaza Satélite',
        codigo: 'T1001',
        marca: 'Hallmark',
        tipo: 'tienda',
        direccion: 'Circuito Centro Comercial #2251, Local R-365',
        colonia: 'Ciudad Satélite',
        municipio: 'Naucalpan de Juárez',
        codigo_postal: '53100',
        estado: 'Estado de México',
        telefono: '5550844548',
        correo: 't1001@lob.com.mx',
        latitud: '19.5102499',
        longitud: '-99.2342176',
    },
    {
        tienda: 'Altaria Aguascalientes',
        codigo: 'N0067',
        marca: 'LOB',
        tipo: 'tienda',
        direccion:
            'Centro Comercial Altaria, Boulevard Zacatecas Norte #849, Local 1073, Planta Baja',
        colonia: 'Los Trojes de Alonso',
        municipio: 'Aguascalientes',
        codigo_postal: '20116',
        estado: 'Aguascalientes',
        telefono: '4493926539',
        correo: 'n0067@lob.com.mx',
        latitud: '21.9240193',
        longitud: '-102.2919999',
    },
    {
        tienda: 'Centro Magno',
        codigo: 'N0044',
        marca: 'LOB',
        tipo: 'tienda',
        direccion:
            'Centro Comercial Centro Magno, Av. Vallarta #2425, Local A-13',
        colonia: 'Arcos Vallarta',
        municipio: 'Guadalajara',
        codigo_postal: '44140',
        estado: 'Jalisco',
        telefono: '3336301064',
        correo: 'n0044@lob.com.mx',
        latitud: '20.6738707',
        longitud: '-103.3805708',
    },
    {
        tienda: 'Fórum Coatzacoalcos',
        codigo: 'N0057',
        marca: 'LOB',
        tipo: 'tienda',
        direccion:
            'Centro Comercial Fórum Coatzacoalcos, Av. Universidad Km 8, Local 77 PB',
        colonia: 'Fovissste',
        municipio: 'Coatzacoalcos',
        codigo_postal: '96537',
        estado: 'Veracruz',
        telefono: '9212106438',
        correo: 'coatzacoalcos@lob.com.mx',
        latitud: '18.14107928',
        longitud: '-94.48810327',
    },
    {
        tienda: 'Galerías Celaya',
        codigo: 'T0004',
        marca: 'LOB',
        tipo: 'tienda',
        direccion: 'Galerías Celaya, Av. Nororiente #200, Local 224',
        colonia: 'Compuertas del Campestre',
        municipio: 'Celaya',
        codigo_postal: '38080',
        estado: 'Guanajuato',
        telefono: '4611594631',
        correo: 't0004@lob.com.mx',
        latitud: '20.5319285',
        longitud: '-100.7792356',
    },
    {
        tienda: 'Galerías Pachuca',
        codigo: 'N0061',
        marca: 'LOB',
        tipo: 'tienda',
        direccion:
            'Centro Comercial Galerías Pachuca, Camino Real de La Plata #100, Locales 236 y 237 B',
        colonia: 'Zona Plateada',
        municipio: 'Pachuca',
        codigo_postal: '42083',
        estado: 'Hidalgo',
        telefono: '7711330025',
        correo: 'n0061@lob.com.mx',
        latitud: '20.09799112',
        longitud: '-98.768302',
    },
    {
        tienda: 'Galerías San Juan del Río',
        codigo: 'T0001',
        marca: 'LOB',
        tipo: 'tienda',
        direccion: 'Avenida Carretera Panamericana Poniente 202',
        colonia: 'Centro',
        municipio: 'San Juan del Río',
        codigo_postal: '76800',
        estado: 'Querétaro',
        telefono: '4272725137',
        correo: 't0001@lob.com.mx',
        latitud: '20.386936',
        longitud: '-100.0122804',
    },
    {
        tienda: 'Galerías Sonora',
        codigo: 'N0110',
        marca: 'LOB',
        tipo: 'tienda',
        direccion: 'Galerías Mall Sonora, Av. Cultura #55, Local Sub Ancla 04',
        colonia: 'Proyecto Río Sonora',
        municipio: 'Hermosillo',
        codigo_postal: '83270',
        estado: 'Sonora',
        telefono: '6622123378',
        correo: 'n0110@lob.com.mx',
        latitud: '29.0664232',
        longitud: '-110.9493332',
    },
];
